name: ThreatNet-Bot-AmmoBot
version: 0.09
abstract: Tail threat messages from a file to ThreatNet
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
requires:
  perl: 5.005
  Fcntl: 0
  Params::Util: 0.05
  Config::Tiny: 2.00
  Class::Inspector: 1.06
  Getopt::Long: 0
  File::Basename: 0
  POE: 0
  POE::Wheel::FollowTail: 0
  POE::Component::IRC: 0
  ThreatNet::Message::IPv4: 0.01
  ThreatNet::Filter: 0.03
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
